name: Docker Image CI

on: [push]
# on:
#   release:
#     types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: saderi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: 
            - linux/amd64 
            - linux/arm64
          tags: 
            - saderi/bifrost:latest
            - saderi/bifrost:${{ github.ref_name }}
